spring.application.name=SPSProjectBackend

# Database Configuration
jasper.report.path=/reports/

spring.datasource.jndi-name=java:/OracleEST

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=DACONS16

spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Logging Configuration
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Connection Pool Configuration (optional but recommended)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000

# Additional Oracle-specific settings
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.security.user.password=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cebevproject@gmail.com
spring.mail.password=jvib gttp ubei iyhj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Set session timeout to 1 minute (60 seconds)
server.servlet.session.timeout=1d



# Server Configuration
server.port=8081

#Redis configuration
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.session.store-type=redis
spring.redis.host=<correct-host>
spring.data.redis.port=6380